# 服务器配置
server:
  port: 8888
  servlet:
    # 访问根路径添加/monitor
    context-path: /monitor

# 数据库相关配置
spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:sqlite::resource:sqlite/test.db
    username: root
    password: root

  # 接口不返回null字段
  jackson:
    default-property-inclusion: non_null


mybatis-plus:
  global-config:
    db-config:
      # 表名不是下划线形式的
      table-underline: false
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false
